# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.8

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

# We use a simple setup with just one stage, since our tests run
# very quickly and setup times for multiple stages would be too
# costly.
stages:
  - lint_and_test

# Set up everything we need to run tests
before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install flake8 tox   # Install basic tools for running tests

lint_and_test:
  stage: lint_and_test
  script:
    - flake8 src tests    # Run PEP8 checks (static check, linting)
    - tox                 # Run tests with tox
  rules:
    # Only run tests when we commit to master branch (to reduce load on GitLab)
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
